### ISSUE TITLE
Twenty Twenty Theme

### ISSUE THREAD

**Issue by tisto** [iRohitSingh/Twenty-Twenty-themes-#5]
# Task

Create an exact copy of the design in the screenshot below. By exact I mean compare the Volto theme with the 2020 screenshot so that I can not spot a difference.

# ToDo

* [ ] Header
* [ ] Headline Block (H1)
* [ ] Image Block (100%)
* [ ] Headline Block (H2)
* [ ] Grid-Block (with Teaser Subblocks)
* [ ] Image Block (100%)
* [ ] Quote Block
* [ ] Separator Block
* [ ] Text Block (with first-character styling via CSS)
* [ ] Call-to-Action Block (title, description, button text, button link)
* [ ] Grid-Block (with image subblock)
* [ ] Footer (can be static)

# URL

https://wordpress.com/theme/twentytwenty/blogdotkitconceptdotcom.wordpress.com

# Screenshot

![screenshot-twenty-twenty](https://user-images.githubusercontent.com/632105/133821549-7ce33880-01ee-416a-8c21-00b0d8e73b5c.png)

**Comment by tisto** [comment]
@iRohitSingh I created a new specification. Please have a look and let's discuss this on Monday.
